name: "Check Team Membership in GH Organisation"
author: "Igor Pecovnik"
description: "Team check"
inputs:
  ORG_MEMBERS:
    required: false
  GITHUB_TOKEN:
    required: false
  TEAM:
    required: false
runs:
  using: "composite"
  steps:
    -  uses: tspascoal/get-user-teams-membership@v3
       id: checkUserMember
       with:
         username: ${{ github.actor }}
         organization: armbian
         team: "${{ inputs.TEAM }}"
         GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Cancel if not a part of the team
      if: ${{ steps.checkUserMember.outputs.isTeamMember == 'false' }}
      uses: "andymckay/cancel-action@0.3"
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
