name: "Create Hetzner Servers"
author: "Igor Pecovnik"
description: "Create Hetzner Cloud servers via matrix strategy"

inputs:
  action:
    required: true
    description: "Action: 'create' or 'delete'"
  server-type:
    required: false
    description: "Hetzner server type (e.g., cax21, cax31, cax41)"
    default: "cax31"
  image:
    required: false
    description: "OS image name"
    default: "ubuntu-24.04"
  ssh-key:
    required: true
    description: "SSH key name in Hetzner Cloud"
  index:
    required: false
    description: "Server index (for matrix builds)"
    default: "0"
  delete-existing:
    required: false
    description: "Delete existing server before creating"
    default: "false"
  hetzner-token:
    required: true
    description: "Hetzner Cloud API token"
  github-token:
    required: false
    description: "GitHub token for runner registration (required for create action)"
  runner-count:
    required: false
    description: "Number of runners per machine"
    default: "2"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      shell: bash
      run: |
        if command -v python3 &> /dev/null; then
          echo "Python3 already installed"
        else
          echo "Installing Python3..."
          apt-get update -qq
          apt-get install -y -qq python3 python3-pip
        fi

    - name: Install hcloud
      shell: bash
      run: |
        pip3 install --break-system-packages hcloud || pip3 install hcloud

    - name: Create/Delete Hetzner Server
      shell: bash
      env:
        HCLOUD_TOKEN: ${{ inputs.hetzner-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        set -e

        CMD="python3 ${{ github.action_path }}/create_servers.py \
          ${{ inputs.action }} \
          --server-type ${{ inputs.server-type }} \
          --image ${{ inputs.image }} \
          --ssh-key ${{ inputs.ssh-key }} \
          --index ${{ inputs.index }}"

        if [[ "${{ inputs.action }}" == "create" ]]; then
          CMD="${CMD} --count 1 --runner-count ${{ inputs.runner-count }}"
          if [[ "${{ inputs.delete-existing }}" == "true" ]]; then
            CMD="${CMD} --delete-existing"
          fi
        else
          CMD="${CMD} --count 1"
        fi

        echo "Running: $CMD"
        RESULT=$(eval $CMD)
        EXIT_CODE=$?

        echo "### Result" >> $GITHUB_STEP_SUMMARY
        echo '```json' >> $GITHUB_STEP_SUMMARY
        echo "${RESULT}" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

        echo "${RESULT}"

        if [ $EXIT_CODE -ne 0 ]; then
          echo "::error::Action failed with exit code ${EXIT_CODE}"
          exit $EXIT_CODE
        fi
