name: "Runner clening"
author: "Igor Pecovnik"
description: "Cleaning self hosted runners"
runs:
  using: "composite"
  steps:

      - name: "Remove JSON files"
        if: ${{ env.RUNNER_USER != runner }}
        shell: bash
        run: |

          sudo rm -rf JSON *.json *.tmp *.parts

      - name: "Remove output folder"
        if: ${{ env.RUNNER_USER != runner }}
        shell: bash
        run: |

          sudo rm -rf cache/toolchain/*
          sudo rm -rf cache/rootfs/*
          sudo rm -rf cache/sources/*
          sudo rm -rf output/{images,debs,debs-beta}/*
          sudo rm -rf userpatches/*

      - name: "Fix permissions"
        if: ${{ env.RUNNER_USER != runner }}
        shell: bash 
        run: |
        
          #sudo chown -R $USER:$USER cache/. 2> /dev/null || true
          sudo chown -R $USER:$USER . 2> /dev/null || true
          #sudo rm -f build/lib/tools/common/__pycache__/bash_declare_parser.cpython-310.pyc 2> /dev/null || true
          sudo rm -f lib/tools/common/__pycache__/bash_declare_parser.cpython-310.pyc 2> /dev/null || true

      - name: Remove dangling Docker images
        if: ${{ env.RUNNER_USER != runner }}
        shell: bash 
        run: |

          # sudo docker image prune -a --force || true

      - name: Remove Other projects
        if: ${{ env.RUNNER_USER != runner }}
        shell: bash 
        run: |

          cd ../..
          PROJECT=$(echo ${{ github.workspace }} | rev | cut -d'/' -f 1 | rev)
          sudo find $(echo ${{ github.workspace }} | rev | cut -d"/" -f3- | rev) \
          -mindepth 1 -maxdepth 1 ! -name "_*" ! -name ${PROJECT} -exec sudo rm -rf {} + || true
